### ISSUE TITLE
Custom/No Transitions

### ISSUE THREAD

**Issue by appinteractive** [lucavenir/go_router_riverpod#10]
Hey thanks for that repo 👍 

But a simple question, how can I customize or even disable the route transitions? I did not found any information beside using GoRoute but nothing with GoRouteData.

**Comment by lucavenir** [comment]
`GoRoute` has [pageBuilder](https://pub.dev/documentation/go_router/latest/go_router/GoRoute/pageBuilder.html), which allows for custom transitions (or disable 'em). You have to manipulate an actual `Page` for that, instead of the simple `Widget` being displayed for that page.

`GoRouteData` has its corresponding `buildPageWithState`.

Just read [the docs](https://pub.dev/documentation/go_router_builder/latest/) for more info.
