### ISSUE TITLE
Integrate User Role Enum Type to User Model

### ISSUE THREAD

**Issue by tonyhart7** [lucavenir/go_router_riverpod#25]
I think we should include that to User main model with Enum Type

**Comment by lucavenir** [comment]
Hi, thanks for the suggestion. I don't think I will merge these two classes, as in a real-case-scenario you don't want to couple authentication with authorization.

Nonetheless, thanks for you input - I'll renamed the classes and the files so that it'll be more specific.

NOTE TO SELF:
- [ ] small refactoring to close this
