### ISSUE TITLE
Question: How to use multiple listenables for GoRouter.refreshListenable

### ISSUE THREAD

**Issue by philitell** [lucavenir/go_router_riverpod#38]
At this point I'm using the "old" watch(someProviderThatShouldTriggerRedirect)-approach from one of your old examples and i'm trying to migrate my code to fit your latest example. The problem of the approach that i'm using at the moment is that the GoRouter-Object is recreated when the provider is updated.

Here is a code-snippet with my current approach:
```
final routerProvider = Provider<GoRouter>((ref) {
  final initializationState = ref.watch(initializationProvider);
  final bool isAuthenticated = ref.watch(isAuthenticatedProvider);
  final initializationAfterLoginState = ref.watch(initializationAfterLoginProvider);

  return GoRouter(
    navigatorKey: mainNavigatorKey,
    initialLocation: InitializationScreen.routeLocation,
    routes: [
      GoRoute(
        name: InitializationScreen.routeName,
        path: InitializationScreen.routeLocation,
        pageBuilder: (context, state) => const NoTransitionPage(child: InitializationScreen()),
      ),
....
```
More details about my usecase:
I have an isAuthenticatedProvider like in your example and an initalizationAfterLoginProvider which is a FutureProvider and performs certain tasks after a user has logged in. So when the user is authenticated the app redirects from LoginScreen to an InitalizationScreen and shows this screen until the initalizationAfterLoginProvider has finished. Next the user should be redirected from InitalizationScreen to HomeScreen.
So i have multiple providers that trigger a redirect. How can i achieve this according to the approach in your lastest example?

### My attempt at an answer
Inside the router.dart-file of your current example project there is this comment:

> /// Obviously, more logic could be implemented here, but again, this is meant to be a simple example.
> /// You can always build more listenables and even merge more than one into a more complex `ChangeNotifier`,
> /// but that's up to your case and out of this scope.

I'm not really used to the ValueNotifier/ChangeNotifier-notiations. How can i merge more than one listenable into a more complex ChangeNotifier?

Does this work the same way like in this old example? https://github.com/lucavenir/go_router_riverpod/blob/84583277e59b0ae025dcda6788ae938d3736f82a/complete_example/lib/router/router_notifier.dart

Thanks for your work on this great repository!

**Comment by lucavenir** [comment]
> The problem of the approach that i'm using at the moment is that the GoRouter-Object is recreated when the provider is updated.

This is why with the new approach we use a simple `ValueNotifier` (a `Listenable`) and a `ref.listen`, which don't trigger rebuilds.

> So i have multiple providers that trigger a redirect. How can i achieve this according to the approach in your lastest example?

Combine these into one single provider first, then `ref.listen` to it like in the we do in the repository.

> I'm not really used to the ValueNotifier/ChangeNotifier-notiations. How can i merge more than one listenable into a more complex ChangeNotifier?

I guess I could change that comment, it might be confusing, but indeed the go-to way is simply to use the simplest refreshable you can think of, `ChangeNotifier` might be overkill. Indeed, as I wrote above, you can isolate the necessary logic into its provider and `ref.listen` to it, triggering changes on your listenable (`ValueNotifier`).

> Thanks for your work on this great repository!

I'm flattered 🙇🏼‍♂️  Unluckily I'm at a stage in which I hate `GoRouter` and routing in general when it comes to Flutter, and this is why I'm not updating this repository as often.
I had so many guides in mind, but I have to wait or to give up on writing them, because of `GoRouter`'s bad APIs, continuous breaking changes, and A LOT of annoying and unexpected bugs.
I hope this will change but I can't see this happening in a _near_ future.

**Comment by lucavenir** [comment]
Of course feel free to ask more questions if anything is unclear.
